"""
ExplanationAgent — StockSense AI
Team NeuralForge | ET GenAI Hackathon 2026

Synthesizes outputs from PatternDetectorAgent + SignalFinderAgent +
NewsSentimentAgent into a plain-English market brief using Gemini 1.5 Flash.
"""

import os
import google.generativeai as genai
from dotenv import load_dotenv
from typing import Dict, Any

load_dotenv()


def _configure_gemini():
    """Configure Gemini with API key from env or Streamlit secrets."""
    try:
        import streamlit as st
        api_key = st.secrets.get("GOOGLE_API_KEY") or os.getenv("GOOGLE_API_KEY")
    except Exception:
        api_key = os.getenv("GOOGLE_API_KEY")
    if api_key:
        genai.configure(api_key=api_key)


def generate_market_explanation(
    pattern_data: Dict[str, Any],
    signal_data: Dict[str, Any],
    news_data: Dict[str, Any] = None
) -> str:
    """
    Generate plain-English market brief from multi-agent outputs.
    Takes structured data from 3 agents, returns Gemini-generated analysis.
    Always includes SEBI disclaimer.
    """
    _configure_gemini()

    ticker = pattern_data.get("ticker", "this stock")
    price = pattern_data.get("current_price", "N/A")
    change_1d = pattern_data.get("price_change_1d", 0)
    company = signal_data.get("company_name", ticker)
    sector = signal_data.get("sector", "N/A")
    fundamentals = signal_data.get("fundamentals", {})

    patterns_text = "\n".join([
        f"- {p['pattern']} (Confidence: {int(p['confidence']*100)}%, Signal: {p['signal']}): {p.get('detail', '')}"
        for p in pattern_data.get("patterns", [])
    ])

    signals_text = "\n".join([
        f"- [{s['strength']}] {s['signal_type']}: {s['message']}"
        for s in signal_data.get("signals", [])
    ])

    news_context = ""
    if news_data:
        news_context = f"""
NEWS SENTIMENT: {news_data.get('overall_sentiment', 'NEUTRAL')} (Score: {news_data.get('sentiment_score', 50)}/100)
Key Themes: {', '.join(news_data.get('key_themes', []))}
News Analysis: {news_data.get('analysis', '')}
"""

    prompt = f"""You are StockSense AI — an expert Indian stock market analyst.
Analyze the following multi-agent data for {company} ({ticker}) and write
a clear, actionable market brief for a retail investor.

MARKET DATA:
- Current Price: ₹{price}
- 1-Day Change: {change_1d}%
- Sector: {sector}
- P/E Ratio: {fundamentals.get('pe_ratio', 'N/A')}
- Dividend Yield: {fundamentals.get('div_yield_pct', 'N/A')}%
- 52-Week High: ₹{fundamentals.get('52w_high', 'N/A')}
- 52-Week Low: ₹{fundamentals.get('52w_low', 'N/A')}
{news_context}
TECHNICAL PATTERNS:
{patterns_text}

OPPORTUNITY SIGNALS:
{signals_text}

Write your response in EXACTLY this format:
## 📊 Market Brief: {ticker}
[2 sentences: what is happening with this stock right now]

## 🔍 What the Charts Say
[Plain-English explanation of technical patterns. No jargon.]

## 💡 Key Opportunity / Risk
[The single most important thing this investor should know today]

## ✅ Suggested Action
[Specific: BUY / HOLD / SELL / WATCH — with a clear condition]

## ⚠️ Important Disclaimer
This analysis is generated by StockSense AI for educational purposes only.
Not SEBI-registered investment advice. Always conduct your own research
and consult a SEBI-registered advisor before making investment decisions.

Tone: Confident but simple. Plain English. Target: retail investor.
Max 300 words total. Use ₹ for Indian currency."""

    try:
        model = genai.GenerativeModel("gemini-1.5-flash")
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"""## 📊 Market Brief: {ticker}

AI analysis temporarily unavailable: {str(e)}

## ⚠️ Disclaimer
Not SEBI-registered investment advice. Do your own research."""


if __name__ == "__main__":
    test_pattern = {
        "ticker": "RELIANCE",
        "current_price": 2847.50,
        "price_change_1d": 1.23,
        "patterns": [{"pattern": "MACD Bullish Crossover", "confidence": 0.82, "signal": "BULLISH", "detail": "Momentum turning up"}]
    }
    test_signal = {
        "company_name": "Reliance Industries Ltd",
        "sector": "Energy",
        "signals": [{"signal_type": "UNDERVALUATION ALERT", "strength": "HIGH", "message": "P/E below 15"}],
        "fundamentals": {"pe_ratio": 12.5, "div_yield_pct": 0.4}
    }
    print("Testing ExplanationAgent...")
    result = generate_market_explanation(test_pattern, test_signal)
    print(result)
